### ISSUE TITLE
Avoin lähdekoodi /Open Source Code License

### ISSUE THREAD

**Issue by varpushaukka** [finnishtransportagency/suomen-vaylat#1]
Hei. Olen nyt FOSS4G Suomi -tapahtumassa ja tämä projekti esiteltiin avoimen lähdekoodin projektina. Tästä puuttuu kuitenkin avoimen lähdekoodin lisenssi. Voisitteko lisätä sellaisen jo tässä vaiheessa vaikka kehitys on kesken? Olisi kiva seurata miten tämä projekti etenee ja ehkä osallistuakin kehitykseen, mutta ilman lisenssiä tämä ei ole avointa lähdekoodia.

In English: Can you add an Open Source License to this project?

**Comment by kuosman** [comment]
Lisätty lisenssi.
